### ISSUE TITLE
Missing development files

### ISSUE THREAD

**Issue by SaphireLattice** [BrightYC/Cyan#4]
Hello! There's not link nor is the lzss library used for compression included in the repo. It's impossible to contribute properly without it, and I am curious as to how this works in first place.

**Comment by ewwhash** [comment]
Just updated README https://github.com/BrightYC/Cyan/commit/54b2155fe0c84e8cda5482228337b116b549c103.
(Btw thanks a lot. Сompletely forgot about it)
