### ISSUE TITLE
Absolutey Awsome

### ISSUE THREAD

**Issue by snaildos** [BrightYC/Cyan#5]
Mate you are bloody awsome, THIS IS WHAT I DREAMED OFF, Some questions:
1) Are you still supporting it?
2) Do you need a API?
3) Are you planning to add raid drive configuration?

**Comment by ewwhash** [comment]
1. I do =)
2. API? For what?
3. RAID works correctly

**Comment by ewwhash** [comment]
btw first screenshow shows raid
![68747470733a2f2f692e696d6775722e636f6d2f575769583274512e706e67](https://user-images.githubusercontent.com/28766913/91859602-14fa2f00-ec84-11ea-86e8-d622463be2bd.png)

https://github.com/BrightYC/Cyan/blob/master/cyan.lua#L240

**Comment by snaildos** [comment]
API for internet booting, thanks for the fast response!

**Comment by ewwhash** [comment]
API? What kind of api you need? From lua REPL or what?

**Comment by snaildos** [comment]
So basically the internet boot you need a URL, if you want I can host stuff on my servers so the code can download files into ram and run it, Like you dont really need a api but a list of OS's you can download would be good. Also a update checker on boot :)

**Comment by ewwhash** [comment]
Checking for updates takes too much space, I have about 40 bytes of free size (I killed too much time to try shrink size of Cyan BIOS D: ) and an internet request taking 3-4 seconds is too much after turning on the PC. List of OS requiring an internet card and I thought of an improved Cyan BIOS with more features, but too lazy. Btw i don't need web server, i have it =) But thx for offer.

**Comment by snaildos** [comment]
Alright I see. This makes clear sense, are you going to make anymore projects?

**Comment by ewwhash** [comment]
I'm not planning anything at the moment =)
I close the issue, chatting here is not a good idea, you can PM me (if you want of course) in discord BrightYC#0604, or Telegram @BrightYC, or in IRC EsperNet - BrightYC too
