### ISSUE TITLE
Locked me out of MineOS

### ISSUE THREAD

**Issue by thevbw** [BrightYC/Cyan#6]
Installed the MineOS app, flashed the BIOS, rebooted, my only option is OpenOS.

**Comment by thevbw** [comment]
Made a quick rewrite of the Lua BIOS to boot MineOS, reflashed Cyan, same issue.

**Comment by ewwhash** [comment]
Well, I just tested the BIOS, everything is ok. Tell me, are you using any OpenComputers emulator or something? Are you using a patched MineOS?

![image](https://user-images.githubusercontent.com/28766913/92975758-6f746600-f4a2-11ea-9700-989cc8ffa10a.png)

**Comment by ewwhash** [comment]
BTW, can you send me your PC configuration? (In OpenComputers)
Are there any blocks attached to your PC like a 3D printer or something like that?

**Comment by hohserg1** [comment]
Yeah, it work good for me. Hardware configuration from /oc_spawnComputer with tier 3 screen
